### ISSUE TITLE
Allow icons dynamic imports

### ISSUE THREAD

**Issue by FreexD** [tabler/tabler-icons#133]
Hello ! What about importing components like this : `import IconFa2 from '@tabler/icons/IconFa2` ?
With Next.js, we could then use this : 

```const IconFa2 = dynamic(() => import('@tabler/icons/IconFa2'));```

Or more dynamic : 

```
const Icon = dynamic(() => import(`@tabler/icons/${name}`));
```

Or maybe export a default, so we can : 

```const Icon = dynamic(() => import('@tabler/icons').then(mod => mod[name]))`;```

What do you think ?

_Originally posted by @matha-io in https://github.com/tabler/tabler-icons/issues/126#issuecomment-829368683_

**Comment by FreexD** [comment]
Hi @matha-io let's discuss the problem in a new issue :) Seems like a good idea to allow this kind of imports! Are you willing to submit a PR or present a PoC how that might be achieved in `tabler-icons`?

**Comment by adambrgmn** [comment]
The last version is already possible today. Though I would not recommend using that version since it would force webpack to bundle _all_ of `@tabler/icons` in the bundle. Which is probably not what the usual project wants.

Also, I'm not sure this would solve the ESM issue either. Correct me if I'm wrong, I don't have a Next project at hand right now to test this on. One might have to do `dynamic(() => import('@tabler/icons/Icon2Fa'), { ssr: false })'`. Otherwise it would [still be loaded server side](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr).

But I like the idea of exposing each icon as a separate module! That would help in situations when the bundler fails to tree shake properly. 

One could technically create their "own library" with only the icons the need for their project:

```js
// components/Icons.js
export Close from '@tabler/icons/IconClose';
export Menu from '@tabler/icons/IconMenu';
// etc...
```

**Comment by matha-io** [comment]
The feature would help build pages with SSG with dynamic content. Let's say we have Markdown Editor which lists content & each content displays a Tabler Icon, we would need to fetch the correct Icon and this feature might help us reduce the number of icons imported.

I don't know `dynamic(() => import('@tabler/icons/Icon2Fa'), { ssr: false })` is okay, since we might want to build the page using SSG (built "server-side").

All the icons 1000+ are available for the content team to use.
For the time being, I'm doing this for the page built with `getStaticProps` : 

```
import * as Icons from '@tabler/icons';

...

const Icon = item.icon ? Icons[`Icon${snakeToCamel(item.icon)}`] : <></>;

return (
  <Flex
    alignItems="center"
    justifyContent="center"
  >
    <Icon size={32} />
  </Flex>
);
```

**Comment by adambrgmn** [comment]
Ah I see. But then you don't mind including the full icon library in your code. But I guess publishing each icon as its own file would solve some parts and then you could use `(await import(`@tabler/icons/${icon}`)).default`.

Note though that I don't think it is possible to use [template string literals with Next.js `dynamic`](https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage), but that is not a concern for this library. You would have to roll your own loading mechanism.

Another issue is in which format to publish the separate files. CommonJS or ESM? ESM is probably more future safe...

**Comment by matha-io** [comment]
I do mind importing everything ^^ But I guess since it's only on SSG, the user don't get the full icon library. I should check that. But if we can come to something more performant, I would be more than happy :)

Search through old issues, they are considering this good : 

```js
// https://github.com/vercel/next.js/issues/2514#issuecomment-313894776
const Components = {
  Red: dynamic(import('../components/red.js')),
  Blue: dynamic(import('../components/blue.js')),
}

export default ({ color }) => {
  const Component = Components[color]
  return <Component />
}
```

I guess ESM should be better indeed, though I am not a pro on the subject !

**Comment by alex-bello** [comment]
> Ah I see. But then you don't mind including the full icon library in your code. But I guess publishing each icon as its own file would solve some parts and then you could use `(await import(`@tabler/icons/${icon}`)).default`.
> 
> Note though that I don't think it is possible to use [template string literals with Next.js `dynamic`](https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage), but that is not a concern for this library. You would have to roll your own loading mechanism.
> 
> Another issue is in which format to publish the separate files. CommonJS or ESM? ESM is probably more future safe...

I think publishing each icon as it's own file is the way to go. I would add the caveat that each file have the icon exported as a named export and as default as well. I use Tabler Icons on a React project and would only be able to take advantage of this change if the files export a default. 

Right now, I am making this work by creating a file for each icon where I export the named export as default and then I just lazy load the icons by importing the individual files as needed.

As for the format, I'd say ESM seems to be the most future-proof way to go.

**Comment by sapkra** [comment]
Is there any update on this topic?

**Comment by codecalm** [comment]
in v2.0 dynamic imports are available! :)

**Comment by ambigos1** [comment]
Can someone attach a dynamic import example?

**Comment by nzyoni** [comment]
> in v2.0 dynamic imports are available! :)

Can we have a working example please?

**Comment by lukasbash** [comment]
Looking for an example too!

**Comment by mfakhrys** [comment]
Here is an example. This is my DynamicIcon component. Hope it helps

```
import { dynamicImports } from "@tabler/icons-react";
import { useEffect, useState } from "react";

const DynamicIcon = ({ name, ...props }) => {
  const [IconComponent, setIconComponent] = useState(null);

  useEffect(() => {
    const loadIcon = async () => {
      try {
        const { default: Icon } = await dynamicImports.default[name]();

        setIconComponent(() => Icon);
      } catch (error) {
        console.error(`Icon "${name}" not found!`, error);
      }
    };

    loadIcon();
  }, [name]);

  if (!IconComponent) return null;

  return <IconComponent {...props} />;
};

export default DynamicIcon;
```

Example usage:

```
<DynamicIcon name="abacus-off" size={24} />
```

**Comment by evolutionxbox** [comment]
`dynamicImports` no longer exists in the package export
