### ISSUE TITLE
[Icon Request] Food allergens/restrictions for menus

### ISSUE THREAD

**Issue by SierraNB** [tabler/tabler-icons#239]
Here's some suggestions (most common allergies/restrictions i could think of)

Food allergies:
- Shellfish
Circle with a shell in it
- Nuts
Circle with a nut in it , maybe a cashew, peanut or almond
- Gluten
Circle with a wheat stalk in it
- Dairy
Circle with a milk container in it. 
This might be difficult to work for a global audience since milk containers differ, but a [classic milk bottle](https://www.thecarycompany.com/media/catalog/product/3/0/30wds4_1.jpg) could work
- Soy
Circle with a soy bean in it's pod

Food restrictions:
- Kosher
Circle with a star of david.
A circle K is often used but that only works for english speakers, a star of david is much more recognizable.
- Halal
Circle with a star and crescent 
- Vegetarian and vegan; 
Same issue as Kosher using english characters, but there's no standard for the symbol and there's many different designs, none can be distinguished from eachother without text. I can think of two possible solutions:
    1. Go with 2 circles with V and VE in them respectively anyway
    2. Create two symbols like [this](https://image.shutterstock.com/image-vector/green-vegan-logo-leafs-sign-260nw-1357603376.jpg) or [this](https://toppng.com/uploads/preview/veganvegetarian-options-transparent-vegetarian-logo-11562860627ajncvleywo.png) and make the user responsible for defining which they represent somewhere in their project with a legend
    
Thank you to everyone at the tabler team.

**Comment by ShahriarKh** [comment]
+1 for this, but three things:
1. The star of David is the symbol of Judaism, and shouldn't be used as the sign of Kosher food.
2. Same for the circle and crescent, as it's the symbol of Islam and not Halal food. For Halal food, there's already a sign: 
[A circle with a "حلال" inside it](https://www.google.com/search?q=halal+logo)
Even though the sign varies by font and color in different countries, I believe a simple "حلال" text, with or without a circle is fine.
3. For food allergies, I'm not sure if there's a universal symbol; However I would like to tweak your idea a little bit and suggest using a triangle instead of a circle since the triangle shape delivers "danger" clearer.
![image](https://user-images.githubusercontent.com/31452340/180416754-3f567dcd-2f44-476b-ac85-c023008e5528.png)
