### ISSUE TITLE
Extremely hard to find icons: Search feels like it got worse

### ISSUE THREAD

**Issue by activenode** [tabler/tabler-icons#960]
Some time ago, when I went to tabler-icons.io and e.g. searched for "user" I found what I needed.

Now, I find a lot of icons which aren't really related to it nor do they fit well. How come?

<img width="1301" alt="image" src="https://github.com/tabler/tabler-icons/assets/9058762/606c65f4-a0ca-4100-81c8-eac8d3bf24af">

**Comment by activenode** [comment]
I gotta add that this happens in unpredictable manners.

**Comment by jpmckearin** [comment]
I don't usually comment "me too", but I am this time simply because I was brought here by https://github.com/mantinedev/mantine on a new project and immediately found this search function on the website to be less than ideal. Maybe you use fuzzy search and recently updated the parameters to be stricter or something, but it makes it difficult for newcomers to discover icons in the lib. For instance, I couldn't search `arrow left` to get the `arrow-left` icon, I had to add the dash and, even then, the icon I was looking for was the 7th result. 
<img width="1709" alt="image" src="https://github.com/tabler/tabler-icons/assets/6679168/e76b868a-c8ee-4aa3-a65c-a410bf558020">
<img width="1728" alt="image" src="https://github.com/tabler/tabler-icons/assets/6679168/54253268-b797-4fbe-8443-04354c95f45a">

**Comment by BG-Software-BG** [comment]
Fuzzy search is used. Surely, it should be improved.

**Comment by hornta** [comment]
I've made an issue about this before but it was closed: https://github.com/tabler/tabler-icons/issues/916

**Comment by BG-Software-BG** [comment]
Icons search has been improved. Give it a try and let me know if it's better now.

**Comment by activenode** [comment]
Seems much better. thanks
